version: 2
updates:
  # NPM updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    reviewers:
      - "DillonBaird"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "DillonBaird"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
