name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or any other branch you want to trigger the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dillonbairdio/nanotrack:latest  # Replace with your Docker Hub username and image repository

    - name: Logout from Docker Hub
      run: docker logout
